[2023-05-31T10:10:05.315+0700] {processor.py:157} INFO - Started process (PID=58328) to work on /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:10:05.316+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task1_20230531.py for tasks to queue
[2023-05-31T10:10:05.316+0700] {logging_mixin.py:149} INFO - [2023-05-31T10:10:05.316+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:10:05.318+0700] {logging_mixin.py:149} INFO - ===============Processing: /home/nhattrieu/airflow/dags/json/task1_20230531100750.json================
[2023-05-31T10:10:05.319+0700] {logging_mixin.py:149} INFO - [2023-05-31T10:10:05.318+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task1_20230531.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task1_20230531.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 58, in get_config
    self.graph.build()
  File "/home/nhattrieu/airflow/dags/dag_builder/graphs/graph.py", line 14, in build
    self.create_vertices()
  File "/home/nhattrieu/airflow/dags/dag_builder/graphs/graph.py", line 18, in create_vertices
    for config in self.config[TASKS]:
KeyError: 'tasks'
[2023-05-31T10:10:05.319+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:10:05.334+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task1_20230531.py took 0.021 seconds
[2023-05-31T10:10:35.574+0700] {processor.py:157} INFO - Started process (PID=58750) to work on /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:10:35.577+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task1_20230531.py for tasks to queue
[2023-05-31T10:10:35.577+0700] {logging_mixin.py:149} INFO - [2023-05-31T10:10:35.577+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:10:35.578+0700] {logging_mixin.py:149} INFO - ===============Processing: /home/nhattrieu/airflow/dags/json/task1_20230531100750.json================
[2023-05-31T10:10:35.580+0700] {logging_mixin.py:149} INFO - [2023-05-31T10:10:35.579+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task1_20230531.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task1_20230531.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 58, in get_config
    self.graph.build()
  File "/home/nhattrieu/airflow/dags/dag_builder/graphs/graph.py", line 14, in build
    self.create_vertices()
  File "/home/nhattrieu/airflow/dags/dag_builder/graphs/graph.py", line 18, in create_vertices
    for config in self.config[TASKS]:
KeyError: 'tasks'
[2023-05-31T10:10:35.580+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:10:35.594+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task1_20230531.py took 0.022 seconds
[2023-05-31T10:11:06.045+0700] {processor.py:157} INFO - Started process (PID=59357) to work on /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:11:06.046+0700] {processor.py:826} INFO - Processing file /home/nhattrieu/airflow/dags/task1_20230531.py for tasks to queue
[2023-05-31T10:11:06.047+0700] {logging_mixin.py:149} INFO - [2023-05-31T10:11:06.047+0700] {dagbag.py:541} INFO - Filling up the DagBag from /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:11:06.048+0700] {logging_mixin.py:149} INFO - ===============Processing: /home/nhattrieu/airflow/dags/json/task1_20230531100750.json================
[2023-05-31T10:11:06.049+0700] {logging_mixin.py:149} INFO - [2023-05-31T10:11:06.048+0700] {dagbag.py:350} ERROR - Failed to import: /home/nhattrieu/airflow/dags/task1_20230531.py
Traceback (most recent call last):
  File "/home/nhattrieu/Documents/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nhattrieu/airflow/dags/task1_20230531.py", line 29, in <module>
    check_daily_datasets = flow_builder.create_flow()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/flow_builder.py", line 3, in create_flow
    self.get_config()
  File "/home/nhattrieu/airflow/dags/dag_builder/builder/graph_flow_builder.py", line 58, in get_config
    self.graph.build()
  File "/home/nhattrieu/airflow/dags/dag_builder/graphs/graph.py", line 14, in build
    self.create_vertices()
  File "/home/nhattrieu/airflow/dags/dag_builder/graphs/graph.py", line 18, in create_vertices
    for config in self.config[TASKS]:
KeyError: 'tasks'
[2023-05-31T10:11:06.049+0700] {processor.py:838} WARNING - No viable dags retrieved from /home/nhattrieu/airflow/dags/task1_20230531.py
[2023-05-31T10:11:06.067+0700] {processor.py:179} INFO - Processing /home/nhattrieu/airflow/dags/task1_20230531.py took 0.025 seconds
